# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfvgui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='virtual_machine_instance_type_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_machine_instance_type_name', models.CharField(max_length=200)),
                ('management_ip_address', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=200)),
                ('image_location', models.CharField(max_length=200)),
                ('configuration_script', models.CharField(max_length=200)),
                ('version_number', models.CharField(max_length=200)),
                ('virtual_machine_type_id', models.CharField(max_length=200)),
                ('minimum_number_of_instances', models.CharField(max_length=200)),
                ('maximum_number_of_instances', models.CharField(max_length=200)),
                ('instantiation_playbook', models.CharField(max_length=200)),
                ('recover_playbook', models.CharField(max_length=200)),
                ('scale_out_playbook', models.CharField(max_length=200)),
                ('scale_in_playbook', models.CharField(max_length=200)),
            ],
        ),
    ]
